openapi: 3.0.0
info:
  title: 'collection API'
  description: 'collection 接口文档'
  version: 0.1.0
servers:
  -
    url: 'http://172.31.0.50:38306'
    description: 虚拟机
paths:
  /asset:
    put:
      tags:
        - updateAsset
      summary: 更新广告素材
      operationId: updateAsset
      requestBody:
        description: 更新广告素材
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssetEdit'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetDetail'
        '500':
          description: 错误
          content:
            application/json:
              schema: {  }
  /asset/list:
    get:
      tags:
        - getAssetList
      summary: 获取广告素材列表
      operationId: getAssetList
      parameters:
        -
          name: page
          in: query
          description: 第几页
          schema:
            type: integer
            example: 1
        -
          name: pagesize
          in: query
          description: 每页多少条数据
          schema:
            type: integer
            example: 20
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetList'
        '500':
          description: 错误
          content:
            application/json:
              schema: {  }
  /brand/all:
    get:
      tags:
        - getAllBrand
      summary: 获取所有品牌
      operationId: getAllBrand
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandList'
        '500':
          description: 错误
          content:
            application/json:
              schema: {  }
  /clue/bulk:
    post:
      tags:
        - ClueBulk
      summary: 批量导入广告线索
      operationId: ClueBulk
      requestBody:
        description: 批量导入广告线索
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema: {  }
        '500':
          description: 错误
          content:
            application/json:
              schema: {  }
  /goods/list:
    get:
      tags:
        - getGoodsList
      summary: 获取商品列表
      operationId: getGoodsList
      parameters:
        -
          name: brandid
          in: query
          description: '品牌 ID'
          schema:
            type: integer
            example: 3397
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsList'
        '500':
          description: 错误
          content:
            application/json:
              schema: {  }
  /goods:
    post:
      tags:
        - addGoods
      summary: 添加商品
      operationId: addGoods
      requestBody:
        description: 添加商品
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddGoods'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Goods'
        '500':
          description: 错误
          content:
            application/json:
              schema: {  }
components:
  schemas:
    AddGoods:
      title: AddGoods
      description: 添加商品
      properties:
        name:
          type: string
        brandid:
          type: integer
      type: object
    App:
      title: App
      description: 媒体模型
      properties:
        appid:
          type: integer
        tite:
          type: string
      type: object
    AssetBrand:
      title: AssetBrand
      description: 请求内容
      properties:
        assetid:
          type: integer
        brandid:
          type: integer
      type: object
    AssetDetail:
      title: AssetDetail
      description: 广告素材详情
      properties:
        assetid:
          type: integer
        url:
          type: string
        url_hash:
          type: string
        ctime:
          type: string
        app:
          $ref: '#/components/schemas/App'
        brand:
          $ref: '#/components/schemas/Brand'
        goods:
          $ref: '#/components/schemas/Goods'
      type: object
    AssetEdit:
      title: AssetEdit
      description: 请求内容
      properties:
        assetid:
          type: integer
        brandid:
          type: integer
        goodsid:
          type: integer
      type: object
    AssetList:
      title: AssetList
      description: 广告线索列表
      properties:
        asset:
          type: array
          items:
            $ref: '#/components/schemas/AssetDetail'
      type: object
    Brand:
      title: Brand
      description: 'Brand 模型'
      properties:
        brandid:
          type: integer
        name:
          type: string
      type: object
    BrandList:
      title: BrandList
      description: 品牌列表
      properties:
        brand:
          type: array
          items:
            $ref: '#/components/schemas/Brand'
      type: object
    Goods:
      title: Goods
      description: 商品模型
      properties:
        goodsid:
          type: integer
        name:
          type: string
        brandid:
          type: integer
      type: object
    GoodsList:
      title: GoodsList
      description: 商品列表
      properties:
        goods:
          type: array
          items:
            $ref: '#/components/schemas/Goods'
      type: object
    RequestBody:
      title: RequestBody
      description: 请求内容
      properties:
        url:
          type: string
          example: 'http://mtrace.play.aiseet.atianqi.com/mkvcollect?a=4.9.0.1018&s=4.3.1.003&k=ACJR7JT12C16&n=4'
        head:
          $ref: '#/components/schemas/RequestHeader'
        extra:
          type: object
      type: object
    RequestHeader:
      title: RequestHeader
      description: 请求头
      properties:
        Host:
          type: string
          example: mtrace.play.aiseet.atianqi.com
        Content-Type:
          type: string
          example: application/octet-stream
        Connection:
          type: string
          example: Keep-Alive
        Content-Encoding:
          type: string
          example: gzip
        Content-Length:
          type: string
          example: '2109'
        User-Agent:
          type: string
          example: 'Dalvik/2.1.0 (Linux; U; Android 6.0.1; ZIDOO_X9S Build/MOB30J)'
        Accept-Encoding:
          type: string
          example: gzip
      type: object
