openapi: 3.0.0
info:
  title: 'collection API'
  description: 'collection 接口文档'
  version: 0.1.0
servers:
  -
    url: 'http://192.168.89.102:38306'
    description: 刘宇航本机
paths:
  /clue/bulk:
    post:
      tags:
        - ClueBulk
      summary: 批量导入广告线索
      operationId: ClueBulk
      consumes:
      - "application/json"
      parameters:
        - name: url
          in: body
          required: true
          schema:
            type: string
            example: 'http://mtrace.play.aiseet.atianqi.com/mkvcollect?a=4.9.0.1018&s=4.3.1.003&k=ACJR7JT12C16&n=4'
        - name: head
          in: body
          required: true
          schema:
            type: object
            example: {}
        - name: extra
          in: body
          schema:
            type: object
            example: {}
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema: {  }
        '500':
          description: 错误
