openapi: 3.0.0
info:
  title: 'collection API'
  description: 'collection 接口文档'
  version: 0.1.0
servers:
  -
    url: 'http://172.31.0.50:38306'
    description: 虚拟机
paths:
  /asset/brand:
    post:
      tags:
        - setAssetBrand
      summary: 设置广告素材的品牌
      operationId: setAssetBrand
      requestBody:
        description: 设置广告素材的品牌
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssetBrand'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema: {  }
        '500':
          description: 错误
          content:
            application/json:
              schema: {  }
  /brand/all:
    post:
      tags:
        - getAllBrand
      summary: 获取所有品牌
      operationId: getAllBrand
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandList'
        '500':
          description: 错误
          content:
            application/json:
              schema: {  }
  /clue/bulk:
    post:
      tags:
        - ClueBulk
      summary: 批量导入广告线索
      operationId: ClueBulk
      requestBody:
        description: 批量导入广告线索
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema: {  }
        '500':
          description: 错误
          content:
            application/json:
              schema: {  }
components:
  schemas:
    AssetBrand:
      title: AssetBrand
      description: 请求内容
      properties:
        assetid:
          type: integer
        brandid:
          type: integer
      type: object
    Brand:
      title: Brand
      description: 'Brand 模型'
      properties:
        brandid:
          type: integer
        name:
          type: string
      type: object
    BrandList:
      title: BrandList
      description: 品牌列表
      properties:
        brand:
          type: array
          items:
            $ref: '#/components/schemas/Brand'
      type: object
    RequestBody:
      title: RequestBody
      description: 请求内容
      properties:
        url:
          type: string
          example: 'http://mtrace.play.aiseet.atianqi.com/mkvcollect?a=4.9.0.1018&s=4.3.1.003&k=ACJR7JT12C16&n=4'
        head:
          $ref: '#/components/schemas/RequestHeader'
        extra:
          type: object
      type: object
    RequestHeader:
      title: RequestHeader
      description: 请求头
      properties:
        Host:
          type: string
          example: mtrace.play.aiseet.atianqi.com
        Content-Type:
          type: string
          example: application/octet-stream
        Connection:
          type: string
          example: Keep-Alive
        Content-Encoding:
          type: string
          example: gzip
        Content-Length:
          type: string
          example: '2109'
        User-Agent:
          type: string
          example: 'Dalvik/2.1.0 (Linux; U; Android 6.0.1; ZIDOO_X9S Build/MOB30J)'
        Accept-Encoding:
          type: string
          example: gzip
      type: object
