openapi: 3.0.0
info:
  title: 'collection API'
  description: 'collection 接口文档'
  version: 0.1.0
servers:
  -
    url: 'http://192.168.89.102:38306'
    description: 刘宇航本机
paths:
  /clue/bulk:
    post:
      tags:
        - ClueBulk
      summary: 批量导入广告线索
      operationId: ClueBulk
      requestBody:
        description: 批量导入广告线索
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema: {  }
        '500':
          description: 错误
          content:
            application/json:
              schema: {  }
components:
  schemas:
    RequestBody:
      title: RequestBody
      description: 请求内容
      properties:
        url:
          type: string
          example: 'http://mtrace.play.aiseet.atianqi.com/mkvcollect?a=4.9.0.1018&s=4.3.1.003&k=ACJR7JT12C16&n=4'
        head:
          $ref: '#/components/schemas/RequestHeader'
        extra:
          type: object
      type: object
    RequestHeader:
      title: RequestHeader
      description: 请求头
      properties:
        Host:
          type: string
          example: mtrace.play.aiseet.atianqi.com
        Content-Type:
          type: string
          example: application/octet-stream
        Connection:
          type: string
          example: Keep-Alive
        Content-Encoding:
          type: string
          example: gzip
        Content-Length:
          type: string
          example: '2109'
        User-Agent:
          type: string
          example: 'Dalvik/2.1.0 (Linux; U; Android 6.0.1; ZIDOO_X9S Build/MOB30J)'
        Accept-Encoding:
          type: string
          example: gzip
      type: object
